const C=[('4–20 mA Scaling', 'Convert a measured 4–20 mA signal into engineering units.', '4-20ma-scaling', 'Instrumentation', '420scale'), ('4–20 mA to Voltage', 'Calculate voltage across a loop resistor.', '4-20ma-voltage', 'Instrumentation', '420volt'), ('4–20 mA Loop Resistor', 'Find the resistor needed for a target voltage.', '4-20ma-resistor', 'Instrumentation', '420res'), ('0–10 V Scaling', 'Convert a 0–10 V signal into engineering units.', '0-10v-scaling', 'Controls', '010scale'), ('Analog Signal Scaling', 'Generic linear scaling for PLC and control signals.', 'analog-scaling', 'Controls', 'analog'), ('Ohm’s Law', 'Calculate voltage, current, resistance, or power.', 'ohms-law', 'Electrical', 'ohm'), ('Voltage Divider', 'Calculate divider output voltage.', 'voltage-divider', 'Electrical', 'divider'), ('PT100 Resistance', 'Estimate PT100 resistance from temperature.', 'pt100-resistance', 'Instrumentation', 'pt100'), ('RTD Temperature', 'Convert PT100 resistance to approximate temperature.', 'rtd-temperature', 'Instrumentation', 'rtd'), ('Pressure Transmitter Scaling', 'Convert a 4–20 mA pressure signal into engineering units.', 'pressure-transmitter', 'Instrumentation', 'pressure')];
function cards(q=""){const h=document.querySelector("#cards");if(!h)return; q=q.toLowerCase();h.innerHTML=C.filter(x=>!q||x.join(" ").toLowerCase().includes(q)).map(x=>`<a class="card" href="calculators/${x[2]}.html"><span class="tag">${x[3]}</span><h3>${x[0]}</h3><p class="muted">${x[1]}</p></a>`).join("")}
function n(id){return Number(document.getElementById(id).value)}function f(x){return Number.isFinite(x)?Number(x.toFixed(6)).toLocaleString():"—"}function inp(id,l,v){return `<div class="field"><label for="${id}">${l}</label><input id="${id}" type="number" step="any" value="${v}"></div>`}
window.addEventListener("DOMContentLoaded",()=>{cards();let s=document.querySelector("#search");if(s)s.addEventListener("input",e=>cards(e.target.value));let c=document.querySelector("[data-calc]");if(!c)return;let t=c.dataset.calc;
const bind=(html,fn)=>{c.innerHTML=html;c.querySelectorAll("input").forEach(e=>e.addEventListener("input",fn));fn()};
if(t==="420scale")bind(`<div class="fields">${inp("a","Lower range","0")}${inp("b","Upper range","100")}${inp("x","Measured mA","13.6")}</div><div class="result"><div class="big" id="o"></div> engineering units</div>`,()=>o.innerHTML=f(n("a")+(n("x")-4)/16*(n("b")-n("a"))));
if(t==="420volt")bind(`<div class="fields">${inp("x","Current (mA)","13.6")}${inp("r","Resistance (Ω)","250")}</div><div class="result"><div class="big" id="o"></div></div>`,()=>o.innerHTML=f(n("x")/1000*n("r"))+" V");
if(t==="420res")bind(`<div class="fields">${inp("x","Current (mA)","20")}${inp("v","Target voltage (V)","5")}</div><div class="result"><div class="big" id="o"></div></div>`,()=>o.innerHTML=f(n("v")/(n("x")/1000))+" Ω");
if(t==="010scale")bind(`<div class="fields">${inp("a","Lower range","0")}${inp("b","Upper range","100")}${inp("x","Measured V","5")}</div><div class="result"><div class="big" id="o"></div></div>`,()=>o.innerHTML=f(n("a")+n("x")/10*(n("b")-n("a"))));
if(t==="analog")bind(`<div class="fields">${inp("a","Input min","4")}${inp("b","Input max","20")}${inp("c","Output min","0")}${inp("d","Output max","100")}${inp("x","Input","12")}</div><div class="result"><div class="big" id="o"></div></div>`,()=>o.innerHTML=f(n("c")+(n("x")-n("a"))/(n("b")-n("a"))*(n("d")-n("c"))));
if(t==="ohm")bind(`<div class="fields">${inp("v","Voltage (V)","24")}${inp("r","Resistance (Ω)","250")}</div><div class="result"><div class="big" id="o"></div><div id="p"></div></div>`,()=>{let v=n("v"),r=n("r"),i=v/r;o.innerHTML=f(i*1000)+" mA";p.innerHTML="Power: "+f(v*i)+" W"});
if(t==="divider")bind(`<div class="fields">${inp("v","Input voltage","24")}${inp("r1","R1 (Ω)","10000")}${inp("r2","R2 (Ω)","10000")}</div><div class="result"><div class="big" id="o"></div></div>`,()=>o.innerHTML=f(n("v")*n("r2")/(n("r1")+n("r2")))+" V");
if(t==="pt100")bind(`<div class="fields">${inp("t","Temperature (°C)","100")}</div><div class="result"><div class="big" id="o"></div></div>`,()=>{let t=n("t");o.innerHTML=f(100*(1+.0039083*t-.0000005775*t*t))+" Ω"});
if(t==="rtd")bind(`<div class="fields">${inp("r","PT100 resistance (Ω)","138.5")}</div><div class="result"><div class="big" id="o"></div></div>`,()=>{let r=n("r"),A=.0039083,B=-.0000005775,disc=A*A-4*B*(1-r/100);o.innerHTML=f((-A+Math.sqrt(disc))/(2*B))+" °C"});
if(t==="pressure")bind(`<div class="fields">${inp("a","Lower pressure","0")}${inp("b","Upper pressure","100")}${inp("x","Measured mA","13.6")}</div><div class="result"><div class="big" id="o"></div></div>`,()=>o.innerHTML=f(n("a")+(n("x")-4)/16*(n("b")-n("a"))));
});